# Generated by Django 3.1.7 on 2021-02-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formule',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
