# Generated by Django 3.2 on 2021-04-30 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='id',
        ),
        migrations.AddField(
            model_name='logs',
            name='UUID_log',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
