# Generated by Django 3.2 on 2021-05-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20210430_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formule',
            old_name='UUID_formule',
            new_name='UUID',
        ),
        migrations.RenameField(
            model_name='logs',
            old_name='UUID_log',
            new_name='UUID',
        ),
        migrations.AlterField(
            model_name='logs',
            name='log',
            field=models.CharField(max_length=500),
        ),
    ]
