# Generated by Django 3.2.3 on 2021-05-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20210504_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='formule',
            name='description_br',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='formule',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='formule',
            name='description_fr',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='formule',
            name='nom_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formule',
            name='nom_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formule',
            name='nom_fr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
