# Generated by Django 3.1.7 on 2021-03-14 19:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('benevole', '0001_initial'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('UUID_association', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=50)),
                ('code_postal', models.IntegerField()),
                ('courriel', models.EmailField(default='', max_length=254)),
                ('fixe', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('portable', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('site_web', models.URLField(default='')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('administrateur', models.CharField(blank=True, default='', help_text="attention : l'admin unique de l'asso ne pourra pas etre vide plus tard et contiendra la FK vers l'admin", max_length=500)),
                ('est_actif', models.BooleanField(default=False)),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
                ('Gestionnaires', models.ManyToManyField(related_name='Benevoles', to='benevole.ProfileBenevole')),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('UUID_abonnement', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('a_jour', models.BooleanField(default=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('facture_nom', models.CharField(max_length=50)),
                ('facture_adresse', models.CharField(max_length=100)),
                ('facture_ville', models.CharField(max_length=50)),
                ('facture_code_postal', models.IntegerField()),
                ('facture_courriel', models.EmailField(default='', max_length=254)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('UUID_association', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='association.association')),
                ('UUID_formule', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='administration.formule')),
            ],
        ),
    ]
