# Generated by Django 3.1.7 on 2021-02-21 13:03

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('UUID_association', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=50)),
                ('code_postal', models.IntegerField(max_length=5)),
                ('fixe', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('portable', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Formule',
            fields=[
                ('UUID_formule', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('cout', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('UUID_abonnement', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('a_jour', models.BooleanField(default=False)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('facture_prenom', models.CharField(max_length=50)),
                ('facture_adresse', models.CharField(max_length=100)),
                ('facture_ville', models.CharField(max_length=50)),
                ('facture_code_postal', models.IntegerField(max_length=5)),
                ('description', models.CharField(max_length=500)),
                ('UUID_formule', models.UUIDField(default=uuid.uuid4)),
                ('UUID_association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.association')),
            ],
        ),
    ]
