# Generated by Django 3.1.7 on 2021-02-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formule',
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='facture_code_postal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='association',
            name='code_postal',
            field=models.IntegerField(),
        ),
    ]
