# Generated by Django 3.1.7 on 2021-03-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('association', '0002_remove_association_gestionnaires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonnement',
            name='UUID_formule',
        ),
        migrations.AddField(
            model_name='abonnement',
            name='formule',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.formule'),
        ),
    ]
