# Generated by Django 3.2.3 on 2021-05-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_auto_20210504_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='description_br',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='description_fr',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='facture_pays',
            field=models.CharField(default='France', max_length=50),
        ),
        migrations.AddField(
            model_name='association',
            name='description_br',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='description_fr',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='pays',
            field=models.CharField(default='France', max_length=50),
        ),
        migrations.AddField(
            model_name='association',
            name='pays_br',
            field=models.CharField(default='France', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='pays_en',
            field=models.CharField(default='France', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='pays_fr',
            field=models.CharField(default='France', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='ville_br',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='ville_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='ville_fr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
