# Generated by Django 3.1.7 on 2021-02-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_formule_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='formule',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
