# Generated by Django 3.2.3 on 2021-05-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0004_auto_20210517_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='pays',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='association',
            name='pays_br',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='pays_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='pays_fr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
