# Generated by Django 3.1.7 on 2021-03-16 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('association', '0004_auto_20210316_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='association',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='association.association'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='formule',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='administration.formule'),
        ),
    ]
