# Generated by Django 3.2.3 on 2021-05-22 13:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0005_auto_20210522_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssoPartenaire',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50, unique='True', verbose_name='association repésentée par le bénévole')),
                ('Association', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='association.association')),
            ],
        ),
    ]
