# Generated by Django 3.1.7 on 2021-03-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0005_auto_20210316_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='est_actif',
            field=models.BooleanField(default=False, help_text="permet de geler une asso :  - qui n'a pas payée - supprimée, pour garder l'historique"),
        ),
    ]
