# Generated by Django 3.2.3 on 2021-05-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0006_assopartenaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assopartenaire',
            name='nom',
            field=models.CharField(max_length=50, unique='False', verbose_name='association repésentée par le bénévole'),
        ),
    ]
