# Generated by Django 3.2.3 on 2021-05-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0007_alter_assopartenaire_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assopartenaire',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='association partenaire'),
        ),
    ]
