# Generated by Django 3.1.7 on 2021-02-21 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0008_auto_20210221_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abonnement',
            old_name='facture_prenom',
            new_name='facture_nom',
        ),
    ]
