# Generated by Django 3.2.4 on 2021-12-10 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20210517_1350'),
        ('association', '0008_alter_assopartenaire_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='formule',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='administration.formule'),
        ),
    ]
