# Generated by Django 3.1.7 on 2021-02-21 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('association', '0009_auto_20210221_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='UUID_formule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administration.formule', unique=True),
        ),
    ]
