# Generated by Django 4.1.5 on 2023-04-05 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0019_remove_profilebenevole_assopartenaire'),
        ('association', '0009_alter_abonnement_formule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='administrateur',
            field=models.ForeignKey(default='', help_text="administrateur référent de l'asso", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to='benevole.profileadministrateur'),
        ),
    ]
