# Generated by Django 3.1.7 on 2021-03-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0009_remove_association_administrateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='administrateur',
            field=models.CharField(blank=True, default='', help_text="attention : l'admin unique de l'asso ne pourra pas etre vide plus tard et contiendra la FK vers l'admin", max_length=500),
        ),
    ]
