# Generated by Django 4.1.5 on 2023-04-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0010_alter_association_administrateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='association',
            old_name='administrateur',
            new_name='referent',
        ),
        migrations.AlterField(
            model_name='association',
            name='est_actif',
            field=models.BooleanField(default=False, help_text="permet de geler une asso :  - qui n'a pas payé - supprimée, pour garder l'historique"),
        ),
    ]
