# Generated by Django 3.1.7 on 2021-02-22 15:47

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0011_auto_20210221_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='association',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='association',
            name='fixe',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='association',
            name='portable',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.CreateModel(
            name='Gestionnaire',
            fields=[
                ('UUID_gestionnaire', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('referent', models.BooleanField(default='False')),
                ('UUID_association', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='association.association')),
            ],
        ),
    ]
