# Generated by Django 3.1.7 on 2021-02-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0012_auto_20210222_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestionnaire',
            name='identifiant',
            field=models.CharField(default='identifiant', max_length=100),
        ),
        migrations.AddField(
            model_name='gestionnaire',
            name='mot_de_passe',
            field=models.CharField(default='mot de passe', max_length=50),
        ),
        migrations.AddField(
            model_name='gestionnaire',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='gestionnaire',
            name='prenom',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
