# Generated by Django 4.1.5 on 2023-04-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0021_remove_profileadministrateur_association_and_more'),
        ('association', '0012_remove_association_referent'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='administrateur',
            field=models.ManyToManyField(blank=True, default='', help_text="administrateurs de l'association", related_name='AdministrateurAssociation', to='benevole.profileadministrateur'),
        ),
    ]
