# Generated by Django 3.1.7 on 2021-02-22 18:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0013_auto_20210222_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestionnaire',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='gestionnaire',
            name='courriel',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='gestionnaire',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='gestionnaire',
            name='fixe',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='gestionnaire',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='gestionnaire',
            name='portable',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='gestionnaire',
            name='role',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='association',
            name='fixe',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='association',
            name='portable',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='gestionnaire',
            name='identifiant',
            field=models.CharField(default='identifiant', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gestionnaire',
            name='mot_de_passe',
            field=models.CharField(default='mot de passe', max_length=100),
        ),
    ]
