# Generated by Django 3.1.7 on 2021-03-18 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0014_auto_20210318_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='administrateur',
        ),
    ]
