# Generated by Django 3.1.7 on 2021-02-23 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('association', '0014_auto_20210222_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestionnaire',
            name='identifiant',
        ),
        migrations.RemoveField(
            model_name='gestionnaire',
            name='mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='gestionnaire',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='gestionnaire',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='gestionnaire',
            name='referent',
        ),
        migrations.AddField(
            model_name='gestionnaire',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
