# Generated by Django 3.1.7 on 2021-03-18 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0010_auto_20210318_2150'),
        ('association', '0015_remove_association_administrateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='administrateur',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to='benevole.profilegestionnaire'),
        ),
    ]
