# Generated by Django 3.1.7 on 2021-02-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0015_auto_20210223_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='administrateur',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
