# Generated by Django 3.1.7 on 2021-02-24 08:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0016_association_administrateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='date_creation',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 24, 8, 47, 56, 177113, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='association',
            name='est_actif',
            field=models.BooleanField(default=False),
        ),
    ]
