# Generated by Django 3.1.7 on 2021-02-24 08:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0017_auto_20210224_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2021, 2, 24, 8, 48, 28, 350805, tzinfo=utc)),
        ),
    ]
