# Generated by Django 3.1.7 on 2021-02-24 17:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0018_auto_20210224_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestionnaire',
            name='courriel',
        ),
        migrations.AlterField(
            model_name='association',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2021, 2, 24, 17, 27, 29, 25693, tzinfo=utc)),
        ),
    ]
