# Generated by Django 3.1.7 on 2021-02-24 21:43

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('association', '0019_auto_20210224_1827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gestionnaire',
            new_name='Profile_Gestionnaire',
        ),
        migrations.AlterField(
            model_name='association',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2021, 2, 24, 21, 43, 27, 345355, tzinfo=utc)),
        ),
    ]
