# Generated by Django 3.1.7 on 2021-02-25 10:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0022_auto_20210224_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilegestionnaire',
            name='UUID_association',
        ),
        migrations.AddField(
            model_name='abonnement',
            name='Gestionnaires',
            field=models.ManyToManyField(to='association.ProfileGestionnaire'),
        ),
        migrations.AlterField(
            model_name='association',
            name='administrateur',
            field=models.CharField(blank=True, default='', help_text="attention : l'admin unique de l'asso ne pourra pas etre vide plus tard et contiendra la FK vers l'admin", max_length=500),
        ),
        migrations.AlterField(
            model_name='profilegestionnaire',
            name='fixe',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='donnée optionnelle', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='profilegestionnaire',
            name='portable',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='donnée obligatoire', max_length=128, region=None),
        ),
    ]
