# Generated by Django 3.1.7 on 2021-02-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0023_auto_20210225_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonnement',
            name='Gestionnaires',
        ),
        migrations.AddField(
            model_name='association',
            name='Gestionnaires',
            field=models.ManyToManyField(to='association.ProfileGestionnaire'),
        ),
    ]
