# Generated by Django 3.1.7 on 2021-02-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0024_auto_20210225_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='Gestionnaires',
            field=models.ManyToManyField(related_name='gestionnaires', to='association.ProfileGestionnaire'),
        ),
    ]
