# Generated by Django 3.1.7 on 2021-03-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0025_auto_20210225_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abonnement',
            old_name='debut',
            new_name='date_debut',
        ),
        migrations.RenameField(
            model_name='abonnement',
            old_name='fin',
            new_name='date_fin',
        ),
    ]
