# Generated by Django 3.1.7 on 2021-03-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0026_auto_20210310_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='site_web',
            field=models.URLField(default=''),
        ),
    ]
