# Generated by Django 3.1.7 on 2021-03-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0027_association_site_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilegestionnaire',
            name='date_de_naissance',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
