# Generated by Django 3.1.7 on 2021-03-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0028_auto_20210311_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilegestionnaire',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
