# Generated by Django 3.1.7 on 2021-03-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0029_profilegestionnaire_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilegestionnaire',
            name='age',
        ),
    ]
