# Generated by Django 3.1.7 on 2021-03-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0031_auto_20210311_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilegestionnaire',
            name='date_de_naissance',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
