# Generated by Django 3.1.7 on 2021-03-10 16:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association', '0026_auto_20210310_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('UUID_equipe', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('responsable_valide', models.BooleanField(help_text='les responsables doivent valider les créneaux choisis')),
                ('responsable_creer', models.BooleanField(help_text='les responsables peuvent creer des bénévoles')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('UUID_planning', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('creneaux', models.BooleanField(help_text='par créneaux fixes ou par entrée libre des bénévoles')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('UUID_equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenement.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('UUID_evenement', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('site_web', models.URLField()),
                ('editable', models.BooleanField(help_text='inscription ouvertes ou non')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('UUID_association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.association')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='UUID_evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenement.evenement'),
        ),
    ]
