# Generated by Django 3.1.7 on 2021-04-04 18:32

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association', '0001_initial'),
        ('benevole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('UUID_equipe', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('responsable_valide', models.BooleanField(help_text='les responsables doivent valider les créneaux choisis')),
                ('responsable_creer', models.BooleanField(help_text='les responsables peuvent creer des bénévoles')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('couleur', colorful.fields.RGBColorField(default='#0d6efd')),
                ('editable', models.BooleanField(default=True, help_text="si non editable, l'équipe est bloqué. Seul un responsable ou + peu l'éditer ou le réouvrir")),
                ('benevole', models.ManyToManyField(blank=True, default='', related_name='BenevolesEquipe', to='benevole.ProfileBenevole')),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('UUID_planning', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('debut', models.DateTimeField(default='')),
                ('fin', models.DateTimeField(default='')),
                ('creneaux', models.BooleanField(help_text='par créneaux fixes ou par entrée libre des bénévoles')),
                ('ouvert_mineur', models.BooleanField(default=True, help_text="possibilité de bloquer l'accès aux mineurs, ex : BAR")),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('couleur', colorful.fields.RGBColorField(default='#0d6efd')),
                ('pas', models.IntegerField(default='30', help_text='pas de reglage des creneaux en minutes: 15 / 30 / 60')),
                ('editable', models.BooleanField(default=True, help_text="si non editable, le planning est bloqué. Seul un responsable ou + peu l'éditer ou le réouvrir")),
                ('benevole', models.ManyToManyField(blank=True, default='', related_name='BenevolesPlanning', to='benevole.ProfileBenevole')),
                ('equipe', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='evenement.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('UUID_poste', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('couleur', colorful.fields.RGBColorField(default='#0d6efd')),
                ('editable', models.BooleanField(default=True, help_text="si non editable, le poste est bloqué. Seul un responsable ou + peu l'éditer ou le réouvrir")),
                ('benevole', models.ManyToManyField(blank=True, default='', related_name='BenevolesPoste', to='benevole.ProfileBenevole')),
                ('planning', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='evenement.planning')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('UUID_evenement', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('site_web', models.URLField(blank=True, default='')),
                ('editable', models.BooleanField(default=True, help_text="si non editable, l'é vènement est bloqué. Seul un responsable ou + peu l'éditer ou le réouvrir")),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('couleur', colorful.fields.RGBColorField(default='#0d6efd')),
                ('association', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='association.association')),
                ('benevole', models.ManyToManyField(blank=True, default='', related_name='BenevolesEvenement', to='benevole.ProfileBenevole')),
                ('organisateur', models.ManyToManyField(blank=True, default='', related_name='OrganisateurEvenement', to='benevole.ProfileOrganisateur')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='evenement',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='evenement.evenement'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='responsable',
            field=models.ManyToManyField(blank=True, default='', related_name='ResponsableEquipe', to='benevole.ProfileResponsable'),
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('UUID_creneau', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(blank=True, default='', help_text='le champs sera écrasé automatiquement', max_length=80)),
                ('debut', models.DateTimeField(default='')),
                ('fin', models.DateTimeField(default='')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('editable', models.BooleanField(default=True, help_text="si non editable, le créneau est bloqué. Seul un responsable ou + peu l'éditer ou le réouvrir")),
                ('benevole', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BenevolesCreneau', to='benevole.profilebenevole')),
                ('poste', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='evenement.poste')),
            ],
            options={
                'verbose_name_plural': 'Creneaux',
            },
        ),
    ]
