# Generated by Django 3.2 on 2021-04-16 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0001_initial'),
        ('evenement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='benevole',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='benevole.profilebenevole'),
        ),
    ]
