# Generated by Django 3.1.7 on 2021-03-16 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0004_auto_20210316_1240'),
        ('evenement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenement',
            old_name='UUID_benevole',
            new_name='benevole',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='UUID_association',
        ),
        migrations.AddField(
            model_name='evenement',
            name='association',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='association.association'),
        ),
    ]
