# Generated by Django 3.1.7 on 2021-03-16 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0005_auto_20210316_1309'),
        ('benevole', '0004_auto_20210316_1309'),
        ('evenement', '0002_auto_20210316_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creneau',
            name='UUID_benevole',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='UUID_benevole',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='UUID_evenement',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='UUID_equipe',
        ),
        migrations.AddField(
            model_name='creneau',
            name='benevole',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='benevole.profilebenevole'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='benevole',
            field=models.ManyToManyField(default='', null=True, related_name='Responsable', to='benevole.ProfileResponsable'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='evenement',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='evenement.evenement'),
        ),
        migrations.AddField(
            model_name='planning',
            name='equipe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='evenement.equipe'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='association',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='association.association'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='planning',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='evenement.planning'),
        ),
    ]
