# Generated by Django 3.1.7 on 2021-03-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0005_auto_20210316_1752'),
        ('evenement', '0003_auto_20210316_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='benevole',
            field=models.ManyToManyField(default='', related_name='Responsable', to='benevole.ProfileResponsable'),
        ),
    ]
