# Generated by Django 3.1.7 on 2021-03-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0003_auto_20210311_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='site_web',
            field=models.URLField(blank=True, default=''),
        ),
    ]
