# Generated by Django 3.1.7 on 2021-03-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0004_auto_20210311_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='ouvert_mineur',
            field=models.BooleanField(default=True, help_text="possibilité de bloquer l'accès aux mineurs, ex : BAR"),
        ),
    ]
