# Generated by Django 3.1.7 on 2021-03-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0004_auto_20210316_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenement',
            old_name='benevole',
            new_name='organisateur',
        ),
    ]
