# Generated by Django 3.2 on 2021-04-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0002_alter_assoorigine_nom'),
        ('evenement', '0004_alter_creneau_benevole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='benevole',
            field=models.ManyToManyField(blank=True, default='', help_text='responsable de poste, ca n a surement pas de sens', null=True, related_name='BenevolesPoste', to='benevole.ProfileBenevole'),
        ),
    ]
