# Generated by Django 3.1.7 on 2021-03-12 16:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0005_planning_ouvert_mineur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('UUID_poste', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('UUID_planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenement.planning')),
            ],
        ),
    ]
