# Generated by Django 3.2 on 2021-04-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0005_alter_poste_benevole'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='creneau_moyen',
            field=models.PositiveSmallIntegerField(choices=[(60, 'Heure'), (90, 'Heure Trente'), (120, 'Deux Heures'), (180, 'Deux Heures Trente'), (240, 'Trois Heures')], default=120, help_text="duree moyen d'un creneau en minutes"),
        ),
        migrations.AlterField(
            model_name='planning',
            name='pas',
            field=models.PositiveSmallIntegerField(choices=[(15, 'Quinze'), (30, 'Trente'), (60, 'Heure')], default=30, help_text='pas de reglage des creneaux en minutes: 15 / 30 / 60'),
        ),
    ]
