# Generated by Django 3.1.7 on 2021-03-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0008_auto_20210318_1428'),
        ('evenement', '0006_auto_20210318_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='organisateur',
            field=models.ManyToManyField(default='', related_name='Organisateur', to='benevole.ProfileOrganisateur'),
        ),
    ]
