# Generated by Django 3.1.7 on 2021-03-18 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0008_auto_20210318_1428'),
        ('evenement', '0007_auto_20210318_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='benevole',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='benevole.profilebenevole'),
        ),
    ]
