# Generated by Django 3.2 on 2021-05-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0008_creneau_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='type',
            field=models.CharField(choices=[('creneau', 'Creneau'), ('benevole', 'Benevole')], default='creneau', help_text='creneau ou dispos de bénévole', max_length=50),
        ),
    ]
