# Generated by Django 3.1.7 on 2021-03-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0009_auto_20210318_1442'),
        ('evenement', '0008_auto_20210318_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='benevole',
            field=models.ManyToManyField(default='', related_name='Bénévole', to='benevole.ProfileBenevole'),
        ),
    ]
