# Generated by Django 3.1.7 on 2021-03-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0009_auto_20210318_1442'),
        ('evenement', '0009_evenement_benevole'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='benevole',
            field=models.ManyToManyField(default='', related_name='Bénévoles', to='benevole.ProfileBenevole'),
        ),
    ]
