# Generated by Django 3.2 on 2021-05-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0011_alter_creneau_poste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenement',
            old_name='date_debut',
            new_name='debut',
        ),
        migrations.RenameField(
            model_name='evenement',
            old_name='date_fin',
            new_name='fin',
        ),
    ]
