# Generated by Django 3.1.7 on 2021-03-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0012_creneau_valide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='valide',
            field=models.BooleanField(default=False, help_text="si validé, le créneau est bloquéseul un responsable ou + peu l'éditer ou le réouvrir"),
        ),
    ]
