# Generated by Django 3.2 on 2021-05-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0012_auto_20210503_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='debut',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='fin',
            field=models.DateTimeField(default=''),
        ),
    ]
