# Generated by Django 3.2 on 2021-05-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0013_auto_20210503_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='editable',
            field=models.BooleanField(default=True, help_text="si non editable, l'évènement est bloqué. Seul un responsable ou + peu l'éditer ou le réouvrir"),
        ),
    ]
