# Generated by Django 3.1.7 on 2021-03-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0013_auto_20210318_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creneau',
            name='valide',
        ),
        migrations.AddField(
            model_name='creneau',
            name='fixe',
            field=models.BooleanField(default=False, help_text="si fixe, le créneau est bloqué. Seul un responsable ou + peu l'éditer ou le réouvrir"),
        ),
    ]
