# Generated by Django 3.2 on 2021-05-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0013_auto_20210503_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creneau',
            old_name='UUID_creneau',
            new_name='UUID',
        ),
        migrations.RenameField(
            model_name='equipe',
            old_name='UUID_equipe',
            new_name='UUID',
        ),
        migrations.RenameField(
            model_name='evenement',
            old_name='UUID_evenement',
            new_name='UUID',
        ),
        migrations.RenameField(
            model_name='planning',
            old_name='UUID_planning',
            new_name='UUID',
        ),
        migrations.RenameField(
            model_name='poste',
            old_name='UUID_poste',
            new_name='UUID',
        ),
    ]
