# Generated by Django 3.1.7 on 2021-03-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0014_auto_20210318_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creneau',
            name='fixe',
        ),
        migrations.AddField(
            model_name='creneau',
            name='editable',
            field=models.BooleanField(default=True, help_text="si non editable, le créneau est bloqué. Seul un responsable ou + peu l'éditer ou le réouvrir"),
        ),
        migrations.AddField(
            model_name='equipe',
            name='editable',
            field=models.BooleanField(default=True, help_text="si non editable, l'équipe est bloqué. Seul un responsable ou + peu l'éditer ou le réouvrir"),
        ),
        migrations.AddField(
            model_name='planning',
            name='editable',
            field=models.BooleanField(default=True, help_text="si non editable, le planning est bloqué. Seul un responsable ou + peu l'éditer ou le réouvrir"),
        ),
        migrations.AddField(
            model_name='poste',
            name='editable',
            field=models.BooleanField(default=True, help_text="si non editable, le poste est bloqué. Seul un responsable ou + peu l'éditer ou le réouvrir"),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='editable',
            field=models.BooleanField(default=True, help_text="si non editable, l'évènement est bloqué. Seul un responsable ou + peu l'éditer ou le réouvrir"),
        ),
    ]
