# Generated by Django 3.1.7 on 2021-03-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0015_auto_20210318_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='editable',
            field=models.BooleanField(default=True, help_text="si non editable, l'é vènement est bloqué. Seul un responsable ou + peu l'éditer ou le réouvrir"),
        ),
    ]
