# Generated by Django 3.2.3 on 2021-05-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0005_rename_uuid_assoorigine_assoorigine_uuid'),
        ('evenement', '0015_auto_20210504_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='benevole',
            field=models.ManyToManyField(blank=True, default='les benevoles peuvent s inscrire a l equipe', related_name='BenevolesEquipe', to='benevole.ProfileBenevole'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='benevole',
            field=models.ManyToManyField(blank=True, default='les benevoles peuvent s inscrire a l envenement', related_name='BenevolesEvenement', to='benevole.ProfileBenevole'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='benevole',
            field=models.ManyToManyField(blank=True, default='les benevoles peuvent s inscrire au planning', related_name='BenevolesPlanning', to='benevole.ProfileBenevole'),
        ),
    ]
