# Generated by Django 3.2.3 on 2021-05-22 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0006_assopartenaire'),
        ('evenement', '0016_auto_20210517_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='assopartenaire',
            field=models.ForeignKey(blank=True, default='', help_text='association pour la quelle le benevole travaille', null=True, on_delete=django.db.models.deletion.PROTECT, to='association.assopartenaire'),
        ),
    ]
