# Generated by Django 3.1.7 on 2021-03-19 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0016_association_administrateur'),
        ('evenement', '0017_auto_20210319_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='association',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='association.association'),
        ),
    ]
