# Generated by Django 3.2.3 on 2021-05-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0006_assopartenaire'),
        ('evenement', '0018_remove_evenement_assopartenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='assopartenaire',
            field=models.ManyToManyField(blank=True, default='', help_text="associations partenaires de 'évèmenement ", to='association.AssoPartenaire'),
        ),
    ]
