# Generated by Django 3.1.7 on 2021-03-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0010_auto_20210318_2150'),
        ('evenement', '0018_auto_20210319_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='benevole',
            field=models.ManyToManyField(default='', related_name='BenevolesEvenement', to='benevole.ProfileBenevole'),
        ),
    ]
