# Generated by Django 3.2.3 on 2021-06-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0019_evenement_assopartenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='vignette',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
