# Generated by Django 3.2.4 on 2021-06-25 17:13

from django.db import migrations, models
import evenement.models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0020_evenement_vignette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='vignette',
            field=models.ImageField(blank=True, upload_to=evenement.models.Evenement.upload_dir_vignette),
        ),
    ]
