# Generated by Django 3.1.7 on 2021-03-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0010_auto_20210318_2150'),
        ('evenement', '0020_auto_20210319_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='organisateur',
            field=models.ManyToManyField(blank=True, default='', related_name='OrganisateurEvenement', to='benevole.ProfileOrganisateur'),
        ),
    ]
