# Generated by Django 3.1.7 on 2021-03-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0010_auto_20210318_2150'),
        ('evenement', '0021_auto_20210319_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='benevole',
            field=models.ManyToManyField(blank=True, default='', related_name='BenevolesCreneau', to='benevole.ProfileBenevole'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='benevole',
            field=models.ManyToManyField(blank=True, default='', related_name='BenevolesEquipe', to='benevole.ProfileBenevole'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='responsable',
            field=models.ManyToManyField(blank=True, default='', related_name='ResponsableEquipe', to='benevole.ProfileResponsable'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='benevole',
            field=models.ManyToManyField(blank=True, default='', related_name='BenevolesPlanning', to='benevole.ProfileBenevole'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='benevole',
            field=models.ManyToManyField(blank=True, default='', related_name='BenevolesPoste', to='benevole.ProfileBenevole'),
        ),
    ]
