# Generated by Django 3.1.7 on 2021-03-23 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0010_auto_20210318_2150'),
        ('evenement', '0022_auto_20210319_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creneau',
            name='benevole',
        ),
        migrations.AddField(
            model_name='creneau',
            name='benevole',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BenevolesCreneau', to='benevole.profilebenevole'),
        ),
    ]
