# Generated by Django 3.2.4 on 2021-06-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0023_alter_creneau_valide_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creneau',
            name='valide_present',
        ),
    ]
