# Generated by Django 3.1.7 on 2021-03-23 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0010_auto_20210318_2150'),
        ('evenement', '0023_auto_20210323_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='benevole',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BenevolesCreneau', to='benevole.profilebenevole'),
        ),
    ]
