# Generated by Django 3.1.7 on 2021-03-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0024_auto_20210323_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
