# Generated by Django 3.1.7 on 2021-03-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0025_poste_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='nom',
            field=models.CharField(blank=True, default='', help_text='le champs sera écrasé automatiquement', max_length=80),
        ),
        migrations.AlterField(
            model_name='planning',
            name='debut',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='planning',
            name='fin',
            field=models.DateTimeField(default=''),
        ),
    ]
