# Generated by Django 3.1.7 on 2021-03-30 20:19

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0026_auto_20210330_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='couleur',
            field=colorful.fields.RGBColorField(default='#0d6efd'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='couleur',
            field=colorful.fields.RGBColorField(default='#0d6efd'),
        ),
        migrations.AddField(
            model_name='planning',
            name='couleur',
            field=colorful.fields.RGBColorField(default='#0d6efd'),
        ),
        migrations.AddField(
            model_name='poste',
            name='couleur',
            field=colorful.fields.RGBColorField(default='#0d6efd'),
        ),
    ]
