# Generated by Django 3.1.7 on 2021-03-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0027_auto_20210330_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='pas',
            field=models.IntegerField(default='30', help_text='pas de reglage des creneaux : 15 / 30 / 60 '),
        ),
    ]
