# Generated by Django 3.2.4 on 2021-07-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0028_alter_creneau_valide_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='courriel_responsable',
            field=models.EmailField(default='', help_text='courriel accessible aux bénévoles en bas de page', max_length=254),
        ),
        migrations.AddField(
            model_name='evenement',
            name='courriel_responsable',
            field=models.EmailField(default='', help_text='courriel accessible aux bénévoles en bas de page', max_length=254),
        ),
    ]
