# Generated by Django 3.2.5 on 2021-08-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0029_auto_20210703_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='ouvert_mineur',
            field=models.BooleanField(default=True, help_text="par défaut, les mineurs peuvent s'inscrire à ce poste"),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='editable',
            field=models.BooleanField(default=True, help_text="si editable, le créneau n'est pas bloqué. pas encore implémenté"),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='editable',
            field=models.BooleanField(default=True, help_text="si éditable, les plannings de l'équipe sont modifiables. pas encore implémenté"),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='editable',
            field=models.BooleanField(default=True, help_text="si éditable, l'évènement est bloqué. pas encore implémenté"),
        ),
        migrations.AlterField(
            model_name='planning',
            name='editable',
            field=models.BooleanField(default=True, help_text='si éditable, les postes du planning sont ouverts. pas encore implémenté'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='editable',
            field=models.BooleanField(default=True, help_text="si editable, le poste est ouvert: Les créneaux sont ouverts aux bénévoles. Sinon les créneaux sont disponibles qu'aux responsables."),
        ),
    ]
