# Generated by Django 3.2.5 on 2021-08-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0030_auto_20210805_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='editable',
        ),
        migrations.AddField(
            model_name='poste',
            name='ouvert',
            field=models.BooleanField(default=True, help_text="si ouvert: Les créneaux sont ouverts aux bénévoles. Sinon les créneaux ne sont disponibles qu'aux responsables."),
        ),
        migrations.AlterField(
            model_name='poste',
            name='ouvert_mineur',
            field=models.BooleanField(default=True, help_text="si sélectionné, les mineurs peuvent s'inscrire à ce poste"),
        ),
    ]
