# Generated by Django 3.2.4 on 2021-08-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0031_auto_20210805_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='ouvert',
            field=models.BooleanField(default=True, help_text="si sélectionné, Les créneaux sont ouverts aux bénévoles. Sinon les créneaux ne sont disponibles qu'aux responsables."),
        ),
    ]
