# Generated by Django 3.2.4 on 2021-08-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0032_alter_poste_ouvert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
