# Generated by Django 3.2.4 on 2021-08-25 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0034_auto_20210822_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='inscription_debut',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='date à partie de laquelle les inscriptions des bénévoles sont possibles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evenement',
            name='inscription_fin',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='date à partie de laquelle les inscriptions des bénévoles sont closes'),
            preserve_default=False,
        ),
    ]
