# Generated by Django 3.2.4 on 2021-08-25 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0035_auto_20210825_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='editable',
            field=models.BooleanField(default=True, help_text="si éditable, l'évènement est ouvert à tous. Sinon, il n'est pas modifiable"),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='inscription_debut',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='date à partir de laquelle les inscriptions des bénévoles sont possibles'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='inscription_fin',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='date à partir de laquelle les inscriptions des bénévoles sont closes'),
        ),
    ]
