# Generated by Django 3.2.4 on 2022-01-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0038_auto_20211105_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='courriel_responsable',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='courriel_responsable',
        ),
    ]
