# Generated by Django 3.2.4 on 2022-01-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0040_evenement_courriel_responsable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenement',
            old_name='courriel_responsable',
            new_name='courriel_organisateur',
        ),
    ]
