# Generated by Django 3.2.4 on 2022-01-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0041_rename_courriel_responsable_evenement_courriel_organisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='courriel_organisateur',
            field=models.EmailField(blank=True, default='', help_text='courriel accessible aux bénévoles en bas de page', max_length=254),
        ),
    ]
