# Generated by Django 3.2.4 on 2022-01-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0043_auto_20220128_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenement_benevole_assopart',
            old_name='benevole',
            new_name='profilebenevole',
        ),
    ]
