# Generated by Django 3.2.4 on 2022-01-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0044_rename_benevole_evenement_benevole_assopart_profilebenevole'),
    ]

    operations = [
    ]
