# Generated by Django 3.2.4 on 2022-01-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0045_auto_20220128_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='benevole',
        ),
    ]
