# Generated by Django 3.2.4 on 2022-01-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0018_alter_profilebenevole_assopartenaire'),
        ('evenement', '0046_remove_evenement_benevole'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='benevole',
            field=models.ManyToManyField(blank=True, default='les benevoles peuvent s inscrire a l envenement', related_name='BenevolesEvenement', through='evenement.evenement_benevole_assopart', to='benevole.ProfileBenevole'),
        ),
    ]
