# Generated by Django 3.2.4 on 2022-01-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0047_evenement_benevole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='benevole',
        ),
    ]
