# Generated by Django 3.2.4 on 2022-01-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0049_evenement_benevole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement_benevole_assopart',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
