# Generated by Django 3.2.4 on 2022-01-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0050_alter_evenement_benevole_assopart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement_benevole_assopart',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
