# Generated by Django 4.0.2 on 2022-03-29 07:51

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0009_alter_abonnement_formule'),
        ('evenement', '0051_alter_evenement_benevole_assopart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='commentaire',
            field=models.TextField(blank=True, default='', help_text='texte expliquant ce que le bénévole peut demander par courriel', max_length=500),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='nom',
            field=models.CharField(blank=True, default='', help_text='le champs sera écrasé automatiquement', max_length=200),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='couleur',
            field=colorful.fields.RGBColorField(default='#e91e63'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='couleur',
            field=colorful.fields.RGBColorField(default='#6610f2'),
        ),
        migrations.AlterField(
            model_name='evenement_benevole_assopart',
            name='asso_part',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='association.assopartenaire'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='couleur',
            field=colorful.fields.RGBColorField(default='#6610f2'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
