# Generated by Django 4.0.6 on 2022-10-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0054_alter_creneau_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='valide_present',
            field=models.BooleanField(blank=True, default=False, help_text="à cocher si le bénévole ne s'est pas présenté"),
        ),
    ]
