# Generated by Django 4.1.5 on 2023-03-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0055_alter_creneau_valide_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='associations_partenaires',
            field=models.BooleanField(default=True, help_text="si coché, on demande aux bénévoles de s'inscrire pour une association partenaire"),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='valide_present',
            field=models.BooleanField(blank=True, default=False, help_text="cocher si le bénévole ne s'est pas présenté"),
        ),
    ]
