# Generated by Django 4.1.5 on 2023-03-14 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0056_evenement_associations_partenaires_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='associations_partenaires',
        ),
    ]
