# Generated by Django 4.1.5 on 2023-03-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0009_alter_abonnement_formule'),
        ('evenement', '0057_remove_evenement_associations_partenaires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='assopartenaire',
            field=models.ManyToManyField(blank=True, default='', help_text='Si les bénévoles doivent choisir une association à représenter, choisir les choix possibles', to='association.assopartenaire'),
        ),
    ]
