# Generated by Django 3.1.7 on 2021-03-15 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Origine',
            fields=[
                ('UUID_origine', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileBenevole',
            fields=[
                ('UUID_benevole', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(blank=True, default='', max_length=50)),
                ('genre', models.CharField(choices=[('MINEUR', 'Mineur'), ('HOMME', 'Homme'), ('FEMME', 'Femme'), ('NSP', 'Ne se prononce pas')], default='NSP', max_length=50)),
                ('date_de_naissance', models.DateField(default='2000-01-01')),
                ('fixe', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='donnée optionnelle', max_length=128, null=True, region=None)),
                ('portable', phonenumber_field.modelfields.PhoneNumberField(help_text='donnée obligatoire', max_length=128, region=None)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('origine', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='benevole.origine')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileResponsable',
            fields=[
                ('UUID_Responsable', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('benevole', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='benevole.profilebenevole')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileOrganisateur',
            fields=[
                ('UUID_Organisateur', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('benevole', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='benevole.profilebenevole')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileGestionnaire',
            fields=[
                ('UUID_gestionnaire', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('referent', models.BooleanField(default=False)),
                ('benevole', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='benevole.profilebenevole')),
            ],
        ),
    ]
