# Generated by Django 3.1.7 on 2021-03-12 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evenement', '0005_planning_ouvert_mineur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePersonne',
            fields=[
                ('UUID_personne', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(blank=True, default='', max_length=50)),
                ('genre', models.CharField(choices=[('MINEUR', 'Mineur'), ('HOMME', 'Homme'), ('FEMME', 'Femme'), ('NSP', 'Ne se prononce pas')], default='NSP', max_length=50)),
                ('date_de_naissance', models.DateField(default='2000-01-01')),
                ('fixe', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='donnée optionnelle', max_length=128, null=True, region=None)),
                ('portable', phonenumber_field.modelfields.PhoneNumberField(help_text='donnée obligatoire', max_length=128, region=None)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Origine',
            fields=[
                ('UUID_origine', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('UUID_personne', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='benevole.profilepersonne')),
            ],
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('UUID_creneau', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(default='', max_length=50)),
                ('debut', models.DateTimeField(blank=True, default='')),
                ('fin', models.DateTimeField(blank=True, default='')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('UUID_personne', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='benevole.profilepersonne')),
                ('UUID_planning', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='evenement.planning')),
            ],
        ),
    ]
