# Generated by Django 3.1.7 on 2021-03-16 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_remove_association_gestionnaires'),
        ('benevole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilegestionnaire',
            name='association',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='association.association'),
        ),
        migrations.AlterField(
            model_name='profilegestionnaire',
            name='benevole',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='benevole.profilebenevole'),
        ),
        migrations.AlterField(
            model_name='profileorganisateur',
            name='benevole',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='benevole.profilebenevole'),
        ),
        migrations.AlterField(
            model_name='profileresponsable',
            name='benevole',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='benevole.profilebenevole'),
        ),
    ]
