# Generated by Django 3.1.7 on 2021-04-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='last name'),
        ),
    ]
