# Generated by Django 3.2 on 2021-05-03 20:38

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0002_alter_assoorigine_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilebenevole',
            name='couleur',
            field=colorful.fields.RGBColorField(default='#6610f2'),
        ),
    ]
