# Generated by Django 3.1.7 on 2021-03-16 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0002_auto_20210316_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebenevole',
            name='origine',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='benevole.origine'),
        ),
    ]
