# Generated by Django 3.1.7 on 2021-03-12 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0002_remove_origine_uuid_personne'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepersonne',
            name='UUID_origine',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='benevole.origine'),
        ),
    ]
