# Generated by Django 3.1.7 on 2021-03-11 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0004_auto_20210311_1624'),
        ('benevole', '0003_auto_20210311_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='UUID_equipe',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='evenement.equipe'),
        ),
        migrations.AddField(
            model_name='creneau',
            name='UUID_personne',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='benevole.profilepersonne'),
        ),
        migrations.AddField(
            model_name='creneau',
            name='UUID_planning',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='evenement.planning'),
        ),
        migrations.AddField(
            model_name='creneau',
            name='debut',
            field=models.DateTimeField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creneau',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='creneau',
            name='fin',
            field=models.DateTimeField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='origine',
            name='UUID_personne',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='benevole.profilepersonne'),
        ),
    ]
