# Generated by Django 3.2 on 2021-05-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0003_profilebenevole_couleur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personne',
            old_name='UUID_personne',
            new_name='UUID',
        ),
        migrations.RenameField(
            model_name='profileadministrateur',
            old_name='UUID_administrateur',
            new_name='UUID',
        ),
        migrations.RenameField(
            model_name='profilebenevole',
            old_name='UUID_benevole',
            new_name='UUID',
        ),
        migrations.RenameField(
            model_name='profileorganisateur',
            old_name='UUID_organisateur',
            new_name='UUID',
        ),
        migrations.RenameField(
            model_name='profileresponsable',
            old_name='UUID_responsable',
            new_name='UUID',
        ),
    ]
