# Generated by Django 3.1.7 on 2021-03-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0003_profilepersonne_uuid_origine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='nom',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>_', max_length=50),
        ),
    ]
