# Generated by Django 3.1.7 on 2021-03-16 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0005_auto_20210316_1309'),
        ('benevole', '0003_auto_20210316_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebenevole',
            name='origine',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='benevole.origine'),
        ),
        migrations.AlterField(
            model_name='profilegestionnaire',
            name='association',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='association.association'),
        ),
        migrations.AlterField(
            model_name='profilegestionnaire',
            name='benevole',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benevole.profilebenevole'),
        ),
        migrations.AlterField(
            model_name='profileorganisateur',
            name='benevole',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benevole.profilebenevole'),
        ),
        migrations.AlterField(
            model_name='profileresponsable',
            name='benevole',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benevole.profilebenevole'),
        ),
    ]
