# Generated by Django 3.1.7 on 2021-03-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0004_auto_20210312_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='nom',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x7f50024afac0>_', max_length=50),
        ),
    ]
