# Generated by Django 3.1.7 on 2021-03-16 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0003_auto_20210316_1309'),
        ('benevole', '0004_auto_20210316_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileorganisateur',
            name='evenement',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='evenement.evenement'),
        ),
        migrations.AddField(
            model_name='profileresponsable',
            name='equipe',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='evenement.equipe'),
        ),
    ]
