# Generated by Django 3.2 on 2021-05-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0004_auto_20210504_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assoorigine',
            old_name='UUID_assoorigine',
            new_name='UUID',
        ),
    ]
