# Generated by Django 3.1.7 on 2021-03-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0004_auto_20210311_2301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Creneau',
        ),
    ]
