# Generated by Django 3.1.7 on 2021-03-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0005_auto_20210312_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='nom',
            field=models.CharField(default="<class 'evenement.models.Planning'>_", max_length=50),
        ),
    ]
