# Generated by Django 3.1.7 on 2021-03-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0005_auto_20210316_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origine',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='association repésentée par le bénévole'),
        ),
    ]
