# Generated by Django 3.1.7 on 2021-03-12 09:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0004_auto_20210311_1624'),
        ('benevole', '0005_delete_creneau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('UUID_creneau', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('debut', models.DateTimeField(blank=True, default='')),
                ('fin', models.DateTimeField(blank=True, default='')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('UUID_equipe', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='evenement.equipe')),
                ('UUID_personne', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='benevole.profilepersonne')),
                ('UUID_planning', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='evenement.planning')),
            ],
        ),
    ]
