# Generated by Django 3.1.7 on 2021-03-18 12:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0006_auto_20210318_1330'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('benevole', '0006_auto_20210317_1553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileBenevole',
            new_name='ProfilePersonne',
        ),
        migrations.RenameField(
            model_name='profilegestionnaire',
            old_name='benevole',
            new_name='personne',
        ),
        migrations.RenameField(
            model_name='profileorganisateur',
            old_name='benevole',
            new_name='personne',
        ),
        migrations.RenameField(
            model_name='profilepersonne',
            old_name='UUID_benevole',
            new_name='UUID_personne',
        ),
        migrations.RenameField(
            model_name='profileresponsable',
            old_name='benevole',
            new_name='personne',
        ),
    ]
