# Generated by Django 3.1.7 on 2021-03-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0006_auto_20210312_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='nom',
            field=models.CharField(default='evenement.Planning.nom_', max_length=50),
        ),
    ]
