# Generated by Django 3.1.7 on 2021-03-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0006_creneau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creneau',
            name='UUID_equipe',
        ),
    ]
