# Generated by Django 3.1.7 on 2021-03-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0007_auto_20210312_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='nom',
            field=models.CharField(default='', max_length=50),
        ),
    ]
