# Generated by Django 3.2.4 on 2021-06-28 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0008_alter_assopartenaire_nom'),
        ('benevole', '0007_alter_personne_assopartenaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='assopartenaire',
        ),
        migrations.AddField(
            model_name='profilebenevole',
            name='assopartenaire',
            field=models.ForeignKey(blank=True, default='', help_text='associations partenaires de l evenement', null=True, on_delete=django.db.models.deletion.PROTECT, to='association.assopartenaire'),
        ),
    ]
