# Generated by Django 3.1.7 on 2021-03-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0008_auto_20210312_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='ouvert_mineur',
            field=models.BooleanField(default=True, help_text='possibilité de ne pas ouvrir ce créneau aux mineurs, ex : BAR'),
        ),
        migrations.AlterField(
            model_name='profilepersonne',
            name='genre',
            field=models.CharField(choices=[('MINEUR', 'Mineur'), ('HOMME', 'Homme'), ('FEMME', 'Femme'), ('NSP', 'Ne se prononce pas')], default='NSP', max_length=50),
        ),
    ]
