# Generated by Django 3.1.7 on 2021-03-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0008_auto_20210318_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilebenevole',
            name='equipe',
        ),
        migrations.AddField(
            model_name='profilebenevole',
            name='message',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
