# Generated by Django 3.1.7 on 2021-03-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0008_auto_20210312_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='debut',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='fin',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
