# Generated by Django 3.2.4 on 2021-06-28 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0008_auto_20210628_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebenevole',
            name='personne',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
