# Generated by Django 3.2.4 on 2021-06-28 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0009_alter_profilebenevole_personne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebenevole',
            name='personne',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
