# Generated by Django 3.1.7 on 2021-03-12 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0005_planning_ouvert_mineur'),
        ('benevole', '0009_auto_20210312_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='UUID_planning',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='evenement.planning'),
        ),
    ]
