# Generated by Django 3.1.7 on 2021-03-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0009_auto_20210312_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creneau',
            name='ouvert_mineur',
        ),
    ]
