# Generated by Django 3.2.4 on 2021-06-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0010_alter_profilebenevole_personne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='date_de_naissance',
            field=models.DateField(null=True),
        ),
    ]
