# Generated by Django 3.2.4 on 2021-07-03 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0011_alter_personne_date_de_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='date_de_naissance',
            field=models.DateField(default=datetime.datetime(2001, 7, 3, 15, 32, 3, 284668), null=True),
        ),
    ]
