# Generated by Django 3.2.5 on 2021-08-01 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0008_alter_assopartenaire_nom'),
        ('benevole', '0012_alter_personne_date_de_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='date_de_naissance',
            field=models.DateField(default=datetime.datetime(2001, 8, 1, 15, 31, 31, 330466), null=True),
        ),
        migrations.AlterField(
            model_name='profilebenevole',
            name='assopartenaire',
            field=models.ForeignKey(blank=True, default='', help_text='associations partenaires que vous voulez représenter', null=True, on_delete=django.db.models.deletion.PROTECT, to='association.assopartenaire', verbose_name=' Association Partenaire'),
        ),
    ]
