# Generated by Django 3.1.7 on 2021-03-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0006_poste'),
        ('benevole', '0013_auto_20210312_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='UUID_poste',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='evenement.poste'),
        ),
    ]
