# Generated by Django 3.2.5 on 2021-08-01 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0013_auto_20210801_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='date_de_naissance',
            field=models.DateField(default=datetime.datetime(2001, 8, 1, 15, 31, 44, 515605), null=True),
        ),
    ]
