# Generated by Django 3.2.4 on 2021-09-01 14:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0015_alter_personne_date_de_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='date_de_naissance',
            field=models.DateField(default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='portable',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="pourra servir à t'appeler le jour J", max_length=128, null=True, region=None),
        ),
    ]
