# Generated by Django 3.2.4 on 2021-11-05 11:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0016_auto_20210901_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='date_de_naissance',
            field=models.DateField(default='2000-01-01', help_text='Requis', null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Option', max_length=500),
        ),
        migrations.AlterField(
            model_name='personne',
            name='email',
            field=models.EmailField(help_text='Requis', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='first_name',
            field=models.CharField(help_text='Requis', max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='fixe',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Option', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='personne',
            name='genre',
            field=models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme'), ('NSP', 'Ne se prononce pas')], default='NSP', help_text='Option', max_length=50),
        ),
        migrations.AlterField(
            model_name='personne',
            name='last_name',
            field=models.CharField(help_text='Requis', max_length=30, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='portable',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Option. Un numéro pour te joindre le jour J.', max_length=128, null=True, region=None),
        ),
    ]
