# Generated by Django 3.2.4 on 2022-01-28 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0009_alter_abonnement_formule'),
        ('benevole', '0017_auto_20211105_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebenevole',
            name='assopartenaire',
            field=models.ForeignKey(blank=True, default='', help_text="associations partenaires que vous voulez représenter, tu n'es pas obligé d'en choisir une.", null=True, on_delete=django.db.models.deletion.PROTECT, to='association.assopartenaire', verbose_name=' Association Partenaire'),
        ),
    ]
