# Generated by Django 4.1.5 on 2023-04-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0019_remove_profilebenevole_assopartenaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileadministrateur',
            name='referent',
            field=models.BooleanField(default=False, help_text='a voir si utile...'),
        ),
    ]
