# Generated by Django 4.1.5 on 2023-04-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benevole', '0020_alter_profileadministrateur_referent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileadministrateur',
            name='association',
        ),
        migrations.RemoveField(
            model_name='profileadministrateur',
            name='referent',
        ),
    ]
